name: Build and Deploy

on:
  push:
    branches: ["master", "action" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Build and Deploy React app to GitHub Pages
      uses: npm run deploy