name: Build and Deploy

on:
  push:
    branches: ["master", "action" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   token: ${{secrets.DEPLOYMENT_PAT}}
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install
        env:
          CI: false
          # git remote set-url origin https://cjschen:${{ secrets.DEPLOYMENT_PAT }}@github.com/${{ github.repository }}.git

      - name: Configure Git
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Run deploy script
        run: npm run deploy -- -m "Deploy React app to GitHub Pages"
        # with:
        #   token: ${{secrets.DEPLOYMENT_PAT}}
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_PAT }}
